### ISSUE TITLE
Rcon connection timeout

### ISSUE THREAD

**Issue by SawyerISnotepic** [MegaAntiCheat/client-backend#147] opened 2024-05-14 00:18 UTC
dunno what this means but it makes MAC not work

exact logs; 
2024-05-14T00:16:05.504485Z  INFO client_backend::settings: Identified current steam user as 76561199237779993
2024-05-14T00:16:05.543855Z  WARN client_backend::player: No steam info cache was found, creating a new one.
2024-05-14T00:16:05.553576Z  INFO client_backend: All required launch arguments are present!
2024-05-14T00:16:05.554421Z  WARN client_backend: No masterbase key is set. If you would like to enable demo uploads, please provision a key at https://megaanticheat.com/provision
2024-05-14T00:16:05.555339Z  INFO client_backend::web: Starting web interface at http://127.0.0.1:3621
2024-05-14T00:16:08.067217Z ERROR client_backend::command_manager: Rcon connection timeout: deadline has elapsed

**Comment by lili7h** [comment] 2024-05-14 01:15
This means that the client isn't connecting to RCon correctly - usually this happens because either rcon isn't running in TF2 (the autoexec.cfg hasn't been run, or the commands are not in there), or because another app on your computer is using port 27015. There are multiple threads in the discord threads channel related to this.

**Comment by Bash-09** [comment] 2024-06-12 01:46
Closing as duplicate of https://github.com/MegaAntiCheat/client-backend/issues/45 (see https://github.com/MegaAntiCheat/client-backend/issues/45#issuecomment-2161916522 and [troubleshooting](https://github.com/MegaAntiCheat/client-backend?tab=readme-ov-file#troubleshooting))

**Closed by Bash-09** 2024-06-12 01:46 UTC
