### ISSUE TITLE
Failed to upload late bytes to masterbase: Server returned 422

### ISSUE THREAD

**Issue by FenekkuKitsune** [MegaAntiCheat/client-backend#190] opened 2024-08-19 11:14 UTC
Only just downloaded this today to contribute as I felt a desire to play tf2 again, but I'm getting the title'd error in the terminal every time a demo is started after the first.

**Comment by StealthSteeler** [comment] 2024-08-19 11:48
That issue is being worked on but it shouldn't impact your ability to upload demos! So continue to use it as you would normally

**Comment by jayceslesar** [comment] 2024-08-19 20:07
Duplicate of #187

**Closed as completed** 2024-08-19 20:07 UTC
