### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by Lisrealyt** [MegaAntiCheat/client-backend#45] opened 2023-08-14 23:49 UTC
Hello, i have a few issues. I think it is because i have a custom steam directory. Here is the log:

"2023-08-14T23:44:18.339810Z DEBUG client_backend::gamefinder: Fetching TF2 Folder
2023-08-14T23:44:18.339967Z DEBUG client_backend::gamefinder: Attempting to open libraryfolders.vdf
2023-08-14T23:44:18.341000Z ERROR client_backend::gamefinder: Failed to read libraryfolders.vdf: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }
2023-08-14T23:44:18.341164Z DEBUG client_backend::settings: Loading steam user login data from Steam directory
2023-08-14T23:44:18.341182Z DEBUG client_backend::gamefinder: Fetching Steam loginusers.vdf
2023-08-14T23:44:18.341366Z ERROR client_backend::gamefinder: Could not locate loginusers.vdf in the Steam dir
2023-08-14T23:44:18.341455Z ERROR client_backend::settings: Could not open loginusers.vdf from Steam dir.
2023-08-14T23:44:18.341705Z ERROR client_backend::settings: Failed to parse loginusers VDF data: Failed parsing input Error:  --> 1:1
  |
1 | 
  | ^---
  |
  = expected pair.
2023-08-14T23:44:18.341766Z DEBUG client_backend::settings: Successfully loaded settings."

**Comment by Bash-09** [comment] 2023-08-15 00:10
Do you have steam installed on a drive other than your C drive by any chance?

**Comment by Lisrealyt** [comment] 2023-08-15 01:02
Yes, I do.

**Comment by Bash-09** [comment] 2023-08-15 01:03
Alright, thanks for the report.

**Comment by Bash-09** [comment] 2023-08-15 11:52
I've made some changes. If you compiled the application yourself please checkout the [Bash09/steamlocate](https://github.com/MegaAntiCheat/client-backend/tree/Bash09/steamlocate) branch, or otherwise here is a compiled windows binary: [client-backend.zip](https://github.com/MegaAntiCheat/client-backend/files/12343766/client-backend.zip).

Please let me know if this fixes the issue you were having.

**Comment by Lisrealyt** [comment] 2023-08-19 18:49
It does work, but it can't find my TF2 directory. How do I add it manually?

**Comment by Lisrealyt** [comment] 2023-08-19 19:00
2023-08-19T18:58:03.089778Z ERROR client_backend: Could not locate TF2 directory: Failed to locate TF2 installation.
2023-08-19T18:58:03.089981Z ERROR client_backend: If you have a valid TF2 installation you can specify it manually by appending ' --tf2_dir "Path to Team Fortress 2 folder"' when running the program.
2023-08-19T18:58:03.090104Z DEBUG LaunchOptions: client_backend::gamefinder: Fetching Steam userdata/<player>/config/localconfig.vdf
2023-08-19T18:58:03.090389Z DEBUG LaunchOptions: client_backend::launchoptions: Found Steam local app config.
2023-08-19T18:58:03.114043Z DEBUG MissingLaunchOptions: client_backend::launchoptions: Checking for missing launch arguments in specified app...
2023-08-19T18:58:03.115000Z  WARN client_backend: Please add the following launch options to your TF2 to allow the MAC client to interface correctly with TF2.
2023-08-19T18:58:03.115641Z  WARN client_backend: Missing launch options: ["-condebug", "-conclearlog", "-usercon", "-g15"]

**Comment by cgcha** [comment] 2023-08-20 02:26
You need to run `cargo run -- --tf2-dir my_tf2_directory` and replace `my_tf2_directory` to wherever your game is.

**Comment by Bash-09** [comment] 2023-08-20 05:57
Do the logs say anything like `INFO client_backend::settings: Identified current steam user as ...`?
Does Steam recognize you have TF2 installed?

The only way I'm able to reproduce this behaviour is if Steam doesn't recognize the TF2 installation (i.e. in your steam library it says "Install" instead of "Play").

**Comment by Lisrealyt** [comment] 2023-08-21 00:14
It is installed. It could be because I installed it over the old one?

**Comment by Lisrealyt** [comment] 2023-08-21 00:26
I also manually added the directory, now it says

WARN client_backend: Missing launch options: ["-condebug", "-conclearlog", "-usercon", "-g15"]

I put in the "missing" launch options.

**Comment by Bash-09** [comment] 2023-08-21 00:27
> I also manually added the directory, now it says
> 
> WARN client_backend: Missing launch options: ["-condebug", "-conclearlog", "-usercon", "-g15"]
> 
> I put in the "missing" launch options.

You should be able to skip this by adding `-i` to the command as well.

**Comment by Lisrealyt** [comment] 2023-08-21 00:29
> > I also manually added the directory, now it says
> > WARN client_backend: Missing launch options: ["-condebug", "-conclearlog", "-usercon", "-g15"]
> > I put in the "missing" launch options.
> 
> You should be able to skip this by adding `-i` to the command as well.

To the launch options?

**Comment by Lisrealyt** [comment] 2023-08-21 00:36
2023-08-21T00:32:15.943413Z  WARN client_backend: Failed to load playerlist, creating new playerlist: IO("C:\\Users\PretendThisIsMyDesktopName\\AppData\\Roaming\\MAC\\MACClient\\config\\playerlist.json", Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." })

**Comment by Bash-09** [comment] 2023-08-21 00:38
That's normal the first time the program successfully runs, it's just creating the initial files. After you run it again that message should disappear.

**Comment by Lisrealyt** [comment] 2023-08-21 00:39
Caused by:
    0: Failed to reconnect to RCon.
    1: RCon connection timed out
    2: deadline has elapsed
2023-08-21T00:39:16.995680Z ERROR client_backend: Failed to run command: Failed to run command

**Comment by Bash-09** [comment] 2023-08-21 00:43
Do you have iTunes installed by any chance? The only time we have seen this issue before is because of AppleDeviceServices, which apparently comes with iTunes. 

If that process is there, try killing it through task manager before starting TF2. 

We will have to investigate changing the rcon port.

**Comment by Lisrealyt** [comment] 2023-08-21 00:48
iTunes is installed but its not active right now.

**Comment by Bash-09** [comment] 2023-08-21 00:53
I believe the AppleDeviceServices that it installs runs when you turn your computer on anyways. 

You can try killing the program, [disabling it permanently](https://smallbusiness.chron.com/prevent-apple-mobile-services-starting-up-automatically-64833.html) (that may stop iTunes from working though) or otherwise there may be a way to change the rcon port which can avoid all of this, but I am yet to test it.

**Comment by lili7h** [comment] 2023-08-21 00:57
specifically, as per #29 , "The more dangerous one here is if an app blocks 27015 on loopback as this blocks the RCon command manager indefinitely.". Some apple services are known to eat that port and stop RCon from working. You can run (on windows) a command like `netstat -an` to view all the listening connections on your machine. If you see any TCP connections on `0.0.0.0` under port `27015` when neither the game nor the client are open, then you know another process is eating your port. 
![image](https://github.com/MegaAntiCheat/client-backend/assets/85176789/b72ccbaa-477b-4396-87cb-68d080496cda)

If you run `netstat -anb` instead it will provide the names of the processes associated with each connection, but that requires the command to be run as admin.

**Comment by Bash-09** [comment] 2023-08-29 12:11
I think this auto-closed from the MR. Didn't mean for that to happen

**Comment by Lisrealyt** [comment] 2023-08-31 21:30
I got a new computer about a week ago, I do not have iTunes installed currently, so I hope this works!

**Comment by Bash-09** [comment] 2024-06-12 01:43
I'm going to close this issue assuming it's resolved. Most connection issues we've seen so far have usually been resolved after ensuring the autoexec is being run properly and trying a different port.

**Closed by Bash-09** 2024-06-12 01:43 UTC
Labels: bug
