### ISSUE TITLE
automatic f1 on bot kick

### ISSUE THREAD

**Issue by Criptc** [MegaAntiCheat/client-backend#137] opened 2024-04-27 04:24 UTC
There should be a system that automatically hits f1 when someone votes to kick a bot

**Comment by Kacey2k** [comment] 2024-04-29 19:32
Impossible without hooking to the game afaik

**Comment by lili7h** [comment] 2024-04-30 00:53
This is possible with live demo parsing, but gets hindered by the demo write-out rate. Can be remedied somewhat with a fully functioning masterbase, as the client calling the vote can tell the MB that they've called a vote, and then MB can tell other connected clients in the same server to spam console echo commands until a demo chunk writes out, so then they can pull out the vote id and determine what vote option to invoke

**Comment by Bash-09** [comment] 2024-06-12 01:48
Closing as duplicate of https://github.com/MegaAntiCheat/client-backend/issues/10

That ticket won't quite cover the entire functionality mentioned here, but it will be best-effort since, as Lilith mentioned, there are significant limitations.

**Closed by Bash-09** 2024-06-12 01:48 UTC
